[package]
name = "lzma-rust2-fuzz"
version = "0.1.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
liblzma = { version = "0.4", features = ["static"] }
lzma-rust2 = { path = "..", default-features = false, features = ["std", "encoder", "lzip", "xz"] }

[features]
default = ["optimization"]
optimization = ["lzma-rust2/optimization"]

[[bin]]
name = "lzma_roundtrip"
path = "fuzz_targets/lzma_roundtrip.rs"
test = false
doc = false

[[bin]]
name = "lzma2_roundtrip"
path = "fuzz_targets/lzma2_roundtrip.rs"
test = false
doc = false

[[bin]]
name = "lzma2_mt_roundtrip"
path = "fuzz_targets/lzma2_mt_roundtrip.rs"
test = false
doc = false

[[bin]]
name = "lzip"
path = "fuzz_targets/lzip.rs"
test = false
doc = false

[[bin]]
name = "bcj2_roundtrip"
path = "fuzz_targets/bcj2_roundtrip.rs"
test = false
doc = false

[[bin]]
name = "bcj2_decode"
path = "fuzz_targets/bcj2_decode.rs"
test = false
doc = false

[[bin]]
name = "lzip_stream"
path = "fuzz_targets/lzip_stream.rs"
test = false
doc = false

[[bin]]
name = "lzma"
path = "fuzz_targets/lzma.rs"
test = false
doc = false

[[bin]]
name = "lzma_stream"
path = "fuzz_targets/lzma_stream.rs"
test = false
doc = false

[[bin]]
name = "lzma2"
path = "fuzz_targets/lzma2.rs"
test = false
doc = false

[[bin]]
name = "xz"
path = "fuzz_targets/xz.rs"
test = false
doc = false

[[bin]]
name = "xz_stream"
path = "fuzz_targets/xz_stream.rs"
test = false
doc = false

[[bin]]
name = "lzma2_stream"
path = "fuzz_targets/lzma2_stream.rs"
test = false
doc = false
